   SELECT a.PERSON_UID,
          y.YEAR_CODE,
          y.YEAR_CODE_DESC,
          y.ACADEMIC_PERIOD,
          y.ACADEMIC_PERIOD_DESC,
          a.FACULTY_ATTRIBUTE,
          a.FACULTY_ATTRIBUTE_DESC,
          a.QUALIFIED_SUBJECT,
          a.QUALIFIED_LEVEL,
          a.FACULTY_COMMENT
   FROM MGT_YEAR_TYPE_DEFINITION y, Z_FACULTY_ATTRIBUTE_TBL a
   WHERE     y.YEAR_TYPE = 'ACYR'
         AND y.ACADEMIC_PERIOD BETWEEN a.ACADEMIC_PERIOD_START
                                   AND a.ACADEMIC_PERIOD_END